AWSTemplateFormatVersion: "2010-09-09"
Description: "Web application to upload images"
Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
  PublicSubnet:
    Description: Public Subnet
    Type: AWS::EC2::Subnet::Id
  InternalTraffic:
    Type: AWS::EC2::SecurityGroup::Id
  PublicTraffic:
    Type: AWS::EC2::SecurityGroup::Id

  ServiceRoleName:
    Description: Service role name
    Type: String
    Default: DefaultServiceRoleName
  ServiceSSMPolicyArn:
    Description: Policy arn for SSM
    Type: String
    Default: arn:aws:iam::aws:policy/AmazonSSMFullAccess

Resources:
  Server:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroupIds:
        - !Ref InternalTraffic
        - !Ref PublicTraffic
      ImageId: ami-0a261c0e5f51090b1
      InstanceType: t2.micro
      IamInstanceProfile: !Ref ServiceInstanceProfile
      SubnetId: !Ref PublicSubnet
      UserData:
        Fn::Base64:
          !Sub |
          #!/bin/bash
          mkdir java
          cd java
          sudo yum install java-17-amazon-corretto-devel -y
          cd ../  
          mkdir app
          aws s3 cp s3://src-articles/ec2-rds/AWS-EC2-RDS-1.0-SNAPSHOT.jar ./app/
#         TODO describe in the article that download sources via UserData could be not a good option, the functional need to configure server only

  ServiceInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref ServiceRole

  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref ServiceRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - !Ref ServiceS3Policy
        - !Ref ServiceSSMPolicyArn

  ServiceS3Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:Get*
            Resource:
              - arn:aws:s3:::src-articles/*
              - arn:aws:s3:::src-articles
