AWSTemplateFormatVersion: "2010-09-09"
Description: "Parent Stack"
Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://src-articles.s3.eu-central-1.amazonaws.com/ec2-rds/CF-vpc.yaml

  DBStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VpcStack
    Properties:
      TemplateURL: https://src-articles.s3.eu-central-1.amazonaws.com/ec2-rds/CF-db.yaml
      Parameters:
        FirstDBSubnet: !GetAtt VpcStack.Outputs.FirstDBSubnet
        SecondDBSubnet: !GetAtt VpcStack.Outputs.SecondDBSubnet
        InternalTraffic: !GetAtt VpcStack.Outputs.InternalTraffic

  ServerStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VpcStack
      - DBStack
    Properties:
      TemplateURL: https://src-articles.s3.eu-central-1.amazonaws.com/ec2-rds/CF-app.yaml
      Parameters:
        VPC: !GetAtt VpcStack.Outputs.VPC
        PublicSubnet: !GetAtt VpcStack.Outputs.PublicSubnet
        InternalTraffic: !GetAtt VpcStack.Outputs.InternalTraffic
        PublicTraffic: !GetAtt VpcStack.Outputs.PublicTraffic
