AWSTemplateFormatVersion: "2010-09-09"
Description: "VPC with public and db subnets"
Parameters:
  AZName:
    Description: Provide the name of AvaliabilityZone
    Type: AWS::EC2::AvailabilityZone::Name
    Default: eu-central-1a
  VPCCidrBlock:
    Description: Provide the CidrBlock for VPC
    Type: String
    Default: 10.0.0.0/16
  PublicCidrBlock:
    Description: Provide the CidrBlock for public subnet
    Type: String
    Default: 10.0.10.0/24
  FirstDBCidrBlock:
    Description: Provide the first CidrBlock for database subnet
    Type: String
    Default: 10.0.11.0/24
  SecondDBCidrBlock:
    Description: Provide the second CidrBlock for database subnet
    Type: String
    Default: 10.0.12.0/24

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCidrBlock

  IGW:
    Type: AWS::EC2::InternetGateway
    Properties: {}

  VPCInternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref IGW
      VpcId: !Ref VPC

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZName
      CidrBlock: !Ref PublicCidrBlock
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: true

  FirstDBSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: eu-central-1b
      CidrBlock: !Ref FirstDBCidrBlock
      VpcId: !Ref VPC

  SecondDBSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: eu-central-1c
      CidrBlock: !Ref SecondDBCidrBlock
      VpcId: !Ref VPC

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  DBRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet

  FirstDBSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref DBRouteTable
      SubnetId: !Ref FirstDBSubnet

  SecondDBSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref DBRouteTable
      SubnetId: !Ref SecondDBSubnet

  PublicIGWRoute:
    Type: AWS::EC2::Route
    Properties:
      GatewayId: !Ref IGW
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0


  PublicTraffic:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      SecurityGroupIngress:
        CidrIp: 0.0.0.0/0
        FromPort: 8080
        ToPort: 8080
        IpProtocol: tcp
      GroupDescription: public access

  InternalTraffic:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: internal access

  InternalTrafficRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref InternalTraffic
      IpProtocol: All
      SourceSecurityGroupId: !GetAtt
        - InternalTraffic
        - GroupId

Outputs:
  VPC:
    Description: The VPC id
    Value: !Ref VPC
  PublicSubnet:
    Description: Public Subnet
    Value: !Ref PublicSubnet
  FirstDBSubnet:
    Description: First DB Subnet
    Value: !Ref FirstDBSubnet
  SecondDBSubnet:
    Description: Second DB Subnet
    Value: !Ref SecondDBSubnet
  PublicTraffic:
    Description: Public Traffic
    Value: !Ref PublicTraffic
  InternalTraffic:
    Description: Internal Traffic
    Value: !Ref InternalTraffic